version: '3.8'

services:

 backend:
    image: exdeo/exdeostuff:admintoollite
    ports:
      - "5001:8080"
    networks:
      - adminnetwork

 frontend:
    image: exdeo/admintoolsfrontend:frontend
    ports:
      - "3000:3000"
    networks:
      - adminnetwork

  database:
    image: exdeo/admintoolmysql
    networks:
      - adminnetwork
    volumes:
      - mysqlvolume:/var/lib/mysql

  handlaren-frontend:
    image: exdeo/handlaren-frontend
    ports:
      - "8001:8001"
    networks:
      - handlaren-network

  handlaren-backend:
    image: exdeo/handlaren-backend
    ports:
      - "8181:8181"
    networks:
      - handlaren-network

networks:
  handlaren-network:
    driver: bridge